name: test_todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  sqflite: ^2.3.3+1
  bloc: ^9.0.0
  equatable: ^2.0.7
  fpdart: ^1.1.0
  path: ^1.9.1
  flutter_slidable: ^3.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
